#!/usr/bin/env node
// Plain Node, no dependencies. Reads tokens/rekta.tokens.json (DTCG format) and
// emits dist/rekta.css (CSS custom properties, light/dark via prefers-color-scheme
// plus a [data-theme] override). `--check` runs a self-check instead of writing: every
// required token path must exist, and every documented text-on-fill pair must hold
// WCAG AA (>= 4.5:1) in both themes.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const tokensPath = join(root, 'tokens', 'rekta.tokens.json');
const outPath = join(root, 'dist', 'rekta.css');
const prefix = 'rekta';

function loadTokens() {
  return JSON.parse(readFileSync(tokensPath, 'utf8'));
}

// Walks the token tree. Calls onToken(dottedPath, tokenNode) for every leaf
// (a node carrying $value), skipping $-prefixed metadata keys.
function walk(node, path, onToken) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    const nextPath = [...path, key];
    if (value && typeof value === 'object' && '$value' in value) {
      onToken(nextPath, value);
    } else if (value && typeof value === 'object') {
      walk(value, nextPath, onToken);
    }
  }
}

function cssVarName(path) {
  return `--${prefix}-${path.join('-')}`;
}

function cssValue(token) {
  const { $type: type, $value: value } = token;
  switch (type) {
    case 'color':
    case 'fluidSize':
    case 'duration':
      return String(value);
    case 'dimension':
      return `${value.value}${value.unit}`;
    case 'fontWeight':
      return String(value);
    case 'fontFamily': {
      const names = Array.isArray(value) ? value : [value];
      return names.map((n) => (n.includes(' ') ? `'${n}'` : n)).join(', ');
    }
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    default:
      throw new Error(`unknown token $type "${type}" at ${JSON.stringify(token)}`);
  }
}

function collect(node, basePath = []) {
  const out = [];
  walk(node, basePath, (path, token) => out.push({ path, token }));
  return out;
}

function declarations(entries, pathPrefix) {
  return entries
    .filter(({ path }) => pathPrefix.every((p, i) => path[i] === p))
    .map(({ path, token }) => `  ${cssVarName(path)}: ${cssValue(token)};`)
    .join('\n');
}

function buildCss(tokens) {
  const lightColor = collect(tokens.color.light, ['color']);
  const darkColor = collect(tokens.color.dark, ['color']);
  const rest = [
    ...collect(tokens.typography, ['typography']),
    ...collect(tokens.spacing, ['spacing']),
    ...collect(tokens.radius, ['radius']),
    ...collect(tokens.motion, ['motion']),
    ...collect(tokens.breakpoint, ['breakpoint'])
  ];

  const restCss = rest.map(({ path, token }) => `  ${cssVarName(path)}: ${cssValue(token)};`).join('\n');
  const lightCss = lightColor.map(({ path, token }) => `  ${cssVarName(path)}: ${cssValue(token)};`).join('\n');
  const darkCss = darkColor.map(({ path, token }) => `  ${cssVarName(path)}: ${cssValue(token)};`).join('\n');

  return `/* Generated by scripts/build-css.mjs from tokens/rekta.tokens.json. Do not edit by hand. */

:root {
  color-scheme: light;
${lightCss}
${restCss}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${darkCss}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${darkCss}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --${prefix}-motion-duration-short: 0s;
    --${prefix}-motion-duration-moderate: 0s;
    --${prefix}-motion-duration-long: 0s;
  }
}

:root[data-motion='off'] {
  --${prefix}-motion-duration-short: 0s;
  --${prefix}-motion-duration-moderate: 0s;
  --${prefix}-motion-duration-long: 0s;
}
`;
}

const REQUIRED_PATHS = [
  'color.light.bg', 'color.light.surface', 'color.light.text.primary', 'color.light.text.contrast-high',
  'color.light.status.info.tile', 'color.light.status.success.tile', 'color.light.status.warning.tile', 'color.light.status.error.tile',
  'color.dark.bg', 'color.dark.surface', 'color.dark.text.primary', 'color.dark.text.contrast-high',
  'color.dark.status.info.tile', 'color.dark.status.success.tile', 'color.dark.status.warning.tile', 'color.dark.status.error.tile',
  'typography.font-family.base', 'typography.size.title', 'spacing.m', 'radius.tile',
  'motion.duration.moderate', 'motion.easing.base', 'breakpoint.mobile', 'breakpoint.ultrawide'
];

function getPath(tokens, dottedPath) {
  const parts = dottedPath.split('.');
  let node = tokens;
  for (const part of parts) {
    if (node == null || typeof node !== 'object' || !(part in node)) return undefined;
    node = node[part];
  }
  return node;
}

// WCAG relative luminance / contrast ratio, hex colors only (the documented pairs are
// all opaque hex fills — rgba tokens like --hover/--shading are never text-on-fill).
function hexToRgb(hex) {
  const m = /^#([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) throw new Error(`expected a 6-digit hex color, got "${hex}"`);
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function relativeLuminance([r, g, b]) {
  const toLinear = (c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  const [rl, gl, bl] = [r, g, b].map(toLinear);
  return 0.2126 * rl + 0.7152 * gl + 0.0722 * bl;
}

function contrastRatio(hexA, hexB) {
  const lA = relativeLuminance(hexToRgb(hexA));
  const lB = relativeLuminance(hexToRgb(hexB));
  const [lighter, darker] = lA > lB ? [lA, lB] : [lB, lA];
  return (lighter + 0.05) / (darker + 0.05);
}

// The documented text-on-fill pairs: the primary text colour must hold AA on every
// status tile fill, in both themes. These are the pairs CONCEPT.md measures for v3.
const AA_PAIRS = ['info', 'success', 'warning', 'error'].flatMap((status) => [
  { theme: 'light', label: `text.primary on status.${status}.tile`, text: 'color.light.text.primary', fill: `color.light.status.${status}.tile` },
  { theme: 'dark', label: `text.primary on status.${status}.tile`, text: 'color.dark.text.primary', fill: `color.dark.status.${status}.tile` }
]);

function runCheck(tokens) {
  const problems = [];

  for (const path of REQUIRED_PATHS) {
    if (getPath(tokens, path) === undefined) problems.push(`missing token: ${path}`);
  }

  if (problems.length === 0) {
    for (const pair of AA_PAIRS) {
      const textHex = getPath(tokens, pair.text).$value;
      const fillHex = getPath(tokens, pair.fill).$value;
      const ratio = contrastRatio(textHex, fillHex);
      const status = ratio >= 4.5 ? 'PASS' : 'FAIL';
      console.log(`${status}  ${pair.theme.padEnd(5)} ${pair.label.padEnd(36)} ${ratio.toFixed(2)}:1`);
      if (ratio < 4.5) problems.push(`AA contrast failure: ${pair.theme} ${pair.label} is only ${ratio.toFixed(2)}:1 (need >= 4.5:1)`);
    }
  }

  if (problems.length > 0) {
    console.error('\nFAILED:');
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  }
  console.log('\nall tokens present, all AA pairs pass');
}

const tokens = loadTokens();

if (process.argv.includes('--check')) {
  runCheck(tokens);
} else {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, buildCss(tokens));
  console.log(`wrote ${outPath}`);
}
